"""Synthetic trail segments, for exercising the analysis half of the pipeline.

Scope warning, because it is easy to over-read a green demo: this generator
validates the *analysis* stages only -- centerline fitting, (s, d) projection,
and Gate scoring. It says nothing about whether Depth Anything 3 can reconstruct
a forest or whether hloc can relocalize a motion-blurred run into it, which is
the actual risk Gate 1 exists to test. Passing here is necessary, not sufficient.

What it does buy: the analysis code can be developed and regression-tested on a
laptop with no GPU, with ground truth known exactly, before any footage exists.
"""

from __future__ import annotations

import numpy as np

from mtb_line.centerline import Centerline
from mtb_line.types import Reconstruction, TrailSegment, Trajectory


def _smooth_noise(n: int, scale: float, correlation: int, rng: np.random.Generator) -> np.ndarray:
    """Low-frequency noise -- rider wander and reloc drift, not white jitter."""
    raw = rng.normal(0.0, 1.0, n + 4 * correlation)
    kernel = np.hanning(2 * correlation + 1)
    smoothed = np.convolve(raw, kernel / kernel.sum(), mode="same")[:n]
    peak = np.abs(smoothed).max()
    return smoothed / max(peak, 1e-9) * scale


def true_centerline(length_m: float = 120.0, spacing: float = 0.05) -> Centerline:
    """An S-bend descending at roughly 12% -- a plausible trail segment."""
    t = np.linspace(0.0, 1.0, int(length_m / spacing))
    xyz = np.stack([
        t * length_m,
        6.0 * np.sin(2.0 * np.pi * 1.2 * t),
        -0.12 * t * length_m,
    ], axis=1)
    return Centerline.from_polyline(xyz, spacing=spacing, smooth_window_m=1.0)


def synthetic_segment(
    n_left: int = 3,
    n_right: int = 3,
    split_window: tuple[float, float] = (48.0, 62.0),
    split_offset_m: float = 1.8,
    wander_m: float = 0.35,
    reloc_drift_m: float = 0.15,
    reloc_noise_m: float = 0.04,
    seed: int = 0,
) -> tuple[TrailSegment, dict[str, str], tuple[float, float]]:
    """Build a segment where riders take a known A/B split.

    The runs differ in sample count (riders move at different speeds), carry
    correlated lateral wander, and each gets its own slow drift standing in for
    residual relocalization error -- the three things that break a naive
    "just average the trajectories" centerline.

    Returns ``(segment, labels, split_window)``.
    """
    rng = np.random.default_rng(seed)
    cl = true_centerline()
    labels: dict[str, str] = {}
    trajectories: list[Trajectory] = []

    plan = [("left", -1.0)] * n_left + [("right", +1.0)] * n_right
    for i, (side, sign) in enumerate(plan):
        run_id = f"{side}{i:02d}"
        labels[run_id] = side

        n = int(rng.integers(280, 460))  # speed differences -> sample-count differences
        s = np.linspace(2.0, cl.length - 2.0, n)

        lateral = _smooth_noise(n, wander_m, max(2, n // 12), rng)
        lo, hi = split_window
        # Ramp the branch in and out so the split has soft edges, as a real
        # line choice does -- riders commit before the feature and rejoin after.
        ramp = np.clip(np.minimum(s - lo, hi - s) / 4.0, 0.0, 1.0)
        lateral += sign * split_offset_m * ramp

        base = cl.interp_xyz(s)
        right = cl.interp_right(s)
        xyz = base + lateral[:, None] * right
        xyz[:, 2] += rng.normal(0.0, 0.03, n)  # rider height bob

        drift = np.stack([_smooth_noise(n, reloc_drift_m, max(2, n // 6), rng) for _ in range(3)], 1)
        xyz = xyz + drift + rng.normal(0.0, reloc_noise_m, xyz.shape)

        speed = np.full(n, cl.length / (n / 30.0))  # crude: constant m/s at 30fps
        trajectories.append(
            Trajectory(
                run_id=run_id,
                xyz=xyz,
                t=np.arange(n) / 30.0,
                speed=speed,
                rider=run_id,
                bike="synthetic",
                conditions="synthetic",
            )
        )

    recon = Reconstruction(
        points=cl.xyz.copy(),
        scale_source="unknown",
        backend="synthetic",
        notes="Generated by mtb_line.synth -- analysis-stage validation only.",
    )
    segment = TrailSegment(segment_id="synthetic-s-bend", reconstruction=recon,
                           trajectories=trajectories)
    return segment, labels, split_window
